const mongoose = require("mongoose");

const PgPersonSchema = new mongoose.Schema({
    fullName:{
      type: String,
      required:true
    },
    email:{
      type:String,
      required:true
    },
    gender:{
      type:String,
      required:true,
    },
    dob:{
      type: Date,
      required:true
    },
    doc_type:{
      type:String,
      required:true
    },
    doc_front:{
      type:String,
      required:true
    },
    doc_back:{
      type:String,
    },
    profile_image:{
      type:String,
      required:true
    },
    mobile_no:{
      type:String,
      required:true
    },
    is_mobile_verified:{
      type:Boolean,
      required:true
    },
    address_line1:{
      type:String,
      required:true
    },
    address_line2:{
      type:String,
    },
    city:{
      type:String,
      required:true
    },
    state:{
      type:String,
      required:true
    },
    country:{
      type:String,
      required:true
    },
    zipcode:{
      type:String,
      required:true
    },
    guardian_fullName:{
      type: String,
      required:true
    },
    guardian_email:{
      type:String,
      required:true
    },
    guardian_gender:{
      type:String,
      required:true,
    },
    guardian_doc_type:{
      type:String,
      required:true
    },
    guardian_doc_front:{
      type:String,
      required:true
    },
    guardian_doc_back:{
      type:String,
    },
    guardian_mobile_no:{
      type:String,
      required:true
    },
    guardian_is_mobile_verified:{
      type:Boolean,
      required:true
    },
    guardian_address_line1:{
      type:String,
      required:true
    },
    guardian_address_line2:{
      type:String,
    },
    guardian_city:{
      type:String,
      required:true
    },
    guardian_state:{
      type:String,
      required:true
    },
    guardian_country:{
      type:String,
      required:true
    },
    guardian_zipcode:{
      type:String,
      required:true
    },
    payment_type:{
      type:String
    },
    payment_status:{
      type:String
    },
    payment_amount:{
      type:String
    }
});

module.exports = mongoose.model("pg_user",PgPersonSchema);